// ********RoostGPT********
/*
Test generated by RoostGPT for test API-test-REST using AI Type Claude AI and AI Model claude-opus-4-5-20251101

RoostTestHash=8a1c903bf9


*/

// ********RoostGPT********
package RestAssured.RoostTest.openapi_configuration.auth;

import io.restassured.specification.RequestSpecification;

import java.io.*;
import java.util.*;

/**
 * UnifiedAuthHandler - A unified authentication handler for REST Assured API testing.
 *
 * This class manages authentication schemes defined in OpenAPI specifications and applies
 * them to REST Assured request specifications. It supports both valid and invalid
 * authentication for positive and negative testing scenarios.
 *
 * Supported authentication types (based on provided specification): - Bearer Token
 * Authentication (JWT)
 *
 * The authValidityType parameter controls whether real or fake credentials are used: -
 * "valid": Uses actual credentials from properties file - "invalid": Uses randomly
 * generated fake credentials for negative testing - null/empty: Defaults to "valid" for
 * backward compatibility
 */
public class UnifiedAuthHandler {

	// Properties loaded from configuration file
	private Properties properties;

	// Map to store registered security schemes
	private Map<String, SecurityScheme> securitySchemes;

	// Properties file name
	private static final String PROPERTIES_FILE = "openapi_configuration_auth.properties";

	// Environment variable prefix for overriding properties
	private static final String ENV_PREFIX = "AUTH_";

	/**
	 * Constructor - Initializes the handler by loading properties and registering
	 * security schemes.
	 */
	public UnifiedAuthHandler() {
		this.properties = new Properties();
		this.securitySchemes = new HashMap<>();
		loadProperties();
		registerOpenApi3Scheme();
	}

	/**
	 * Loads authentication properties from the classpath properties file. Properties can
	 * be overridden by environment variables with the AUTH_ prefix.
	 */
	private void loadProperties() {
		// Try to load from classpath
		try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream(PROPERTIES_FILE)) {
			if (inputStream != null) {
				properties.load(inputStream);
			}
			else {
				System.err.println("Warning: " + PROPERTIES_FILE
						+ " not found in classpath. Using defaults and environment variables.");
			}
		}
		catch (IOException e) {
			System.err.println("Warning: Error loading " + PROPERTIES_FILE + ": " + e.getMessage());
		}

		// Override with environment variables
		for (String key : properties.stringPropertyNames()) {
			String envKey = ENV_PREFIX + key;
			String envValue = System.getenv(envKey);
			if (envValue != null && !envValue.isEmpty()) {
				properties.setProperty(key, envValue);
			}
		}
	}

	/**
	 * Registers OpenAPI 3.0+ security schemes defined in the specification. This method
	 * is called during initialization to set up all available security schemes.
	 */
	private void registerOpenApi3Scheme() {
		// Register bearerAuth - JWT Bearer Token Authentication
		SecurityScheme bearerAuthScheme = new SecurityScheme();
		bearerAuthScheme.setName("bearerAuth");
		bearerAuthScheme.setType("http");
		bearerAuthScheme.setScheme("bearer");
		bearerAuthScheme.setBearerFormat("JWT");
		bearerAuthScheme.setDescription(
				"JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"");
		securitySchemes.put("bearerAuth", bearerAuthScheme);
	}

	/**
	 * Applies authentication to a request specification using the specified scheme. This
	 * is the main method with authValidityType parameter for controlling credential
	 * validity.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeName The name of the security scheme to apply
	 * @param authValidityType "valid" for real credentials, "invalid" for fake
	 * credentials. Defaults to "valid" if null or empty.
	 * @return The modified request specification with authentication applied
	 */
	public RequestSpecification applyAuth(RequestSpecification requestSpec, String schemeName,
			String authValidityType) {
		// Normalize authValidityType - default to "valid" if null or empty
		if (authValidityType == null || authValidityType.trim().isEmpty()) {
			authValidityType = "valid";
		}

		SecurityScheme scheme = securitySchemes.get(schemeName);
		if (scheme == null) {
			System.err
				.println("Warning: Security scheme '" + schemeName + "' not found. Returning unmodified request.");
			return requestSpec;
		}

		String type = scheme.getType();
		String schemeType = scheme.getScheme();

		// Handle HTTP authentication schemes (Bearer)
		if ("http".equalsIgnoreCase(type)) {
			if ("bearer".equalsIgnoreCase(schemeType)) {
				return applyBearerAuth(requestSpec, scheme, authValidityType);
			}
		}

		System.err.println("Warning: Unsupported authentication type for scheme '" + schemeName
				+ "'. Returning unmodified request.");
		return requestSpec;
	}

	/**
	 * Applies authentication to a request specification using the specified scheme.
	 * Backward compatible overload that defaults to "valid" authentication.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeName The name of the security scheme to apply
	 * @return The modified request specification with valid authentication applied
	 */
	public RequestSpecification applyAuth(RequestSpecification requestSpec, String schemeName) {
		return applyAuth(requestSpec, schemeName, "valid");
	}

	/**
	 * Applies multiple authentication schemes to a request specification.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeNames List of security scheme names to apply
	 * @param authValidityType "valid" for real credentials, "invalid" for fake
	 * credentials. Defaults to "valid" if null or empty.
	 * @return The modified request specification with all authentications applied
	 */
	public RequestSpecification applyMultipleAuth(RequestSpecification requestSpec, List<String> schemeNames,
			String authValidityType) {
		// Normalize authValidityType - default to "valid" if null or empty
		if (authValidityType == null || authValidityType.trim().isEmpty()) {
			authValidityType = "valid";
		}

		RequestSpecification result = requestSpec;
		for (String schemeName : schemeNames) {
			result = applyAuth(result, schemeName, authValidityType);
		}
		return result;
	}

	/**
	 * Applies multiple authentication schemes to a request specification. Backward
	 * compatible overload that defaults to "valid" authentication.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param schemeNames List of security scheme names to apply
	 * @return The modified request specification with all valid authentications applied
	 */
	public RequestSpecification applyMultipleAuth(RequestSpecification requestSpec, List<String> schemeNames) {
		return applyMultipleAuth(requestSpec, schemeNames, "valid");
	}

	/**
	 * Applies Bearer Token authentication to the request specification.
	 * @param requestSpec The REST Assured request specification to modify
	 * @param scheme The security scheme containing bearer token configuration
	 * @param authValidityType "valid" for real token, "invalid" for fake token
	 * @return The modified request specification with Bearer authentication applied
	 */
	private RequestSpecification applyBearerAuth(RequestSpecification requestSpec, SecurityScheme scheme,
			String authValidityType) {
		// Normalize authValidityType - default to "valid" if null or empty
		if (authValidityType == null || authValidityType.trim().isEmpty()) {
			authValidityType = "valid";
		}

		String token;

		if ("invalid".equalsIgnoreCase(authValidityType)) {
			// Generate invalid/fake token for negative testing
			token = generateInvalidValue("invalid_token");
		}
		else {
			// Use valid token from properties
			token = getPropertyWithEnvOverride("bearerAuth_token");
			if (token == null || token.isEmpty()) {
				System.err.println(
						"Warning: Bearer token not configured. Set 'bearerAuth_token' in properties or 'AUTH_bearerAuth_token' environment variable.");
				token = "";
			}
		}

		// Apply Bearer token to Authorization header
		return requestSpec.header("Authorization", "Bearer " + token);
	}

	/**
	 * Checks if a security scheme with the given name is registered.
	 * @param schemeName The name of the security scheme to check
	 * @return true if the scheme exists, false otherwise
	 */
	public boolean hasScheme(String schemeName) {
		return securitySchemes.containsKey(schemeName);
	}

	/**
	 * Gets the base URL for API requests from properties.
	 * @return The configured base URL or default value
	 */
	public String getBaseUrl() {
		return getPropertyWithEnvOverride("api_baseUrl", "http://localhost:8080/OpenAPIExample/");
	}

	/**
	 * Gets the current environment setting from properties.
	 * @return The configured environment or default value "dev"
	 */
	public String getEnvironment() {
		return getPropertyWithEnvOverride("api_environment", "dev");
	}

	/**
	 * Gets a property value with environment variable override support.
	 * @param key The property key
	 * @return The property value or null if not found
	 */
	private String getPropertyWithEnvOverride(String key) {
		return getPropertyWithEnvOverride(key, null);
	}

	/**
	 * Gets a property value with environment variable override support and default value.
	 * @param key The property key
	 * @param defaultValue The default value if property is not found
	 * @return The property value, environment override, or default value
	 */
	private String getPropertyWithEnvOverride(String key, String defaultValue) {
		// Check environment variable first
		String envKey = ENV_PREFIX + key;
		String envValue = System.getenv(envKey);
		if (envValue != null && !envValue.isEmpty()) {
			return envValue;
		}

		// Fall back to properties file
		return properties.getProperty(key, defaultValue);
	}

	/**
	 * Generates an invalid/fake value for negative testing scenarios. Uses UUID to ensure
	 * uniqueness of generated values.
	 * @param prefix The prefix to use for the generated value
	 * @return A random string in the format: prefix_UUID
	 */
	private String generateInvalidValue(String prefix) {
		return prefix + "_" + UUID.randomUUID().toString();
	}

	/**
	 * Returns all registered security scheme names.
	 * @return Set of registered security scheme names
	 */
	public Set<String> getRegisteredSchemes() {
		return Collections.unmodifiableSet(securitySchemes.keySet());
	}

	/**
	 * Inner class representing a security scheme configuration. Stores all relevant
	 * details parsed from the OpenAPI specification.
	 */
	private static class SecurityScheme {

		private String name;

		private String type;

		private String scheme;

		private String bearerFormat;

		private String description;

		private String in;

		private String paramName;

		private String flow;

		private String authorizationUrl;

		private String tokenUrl;

		private String openIdConnectUrl;

		private Map<String, String> scopes;

		public SecurityScheme() {
			this.scopes = new HashMap<>();
		}

		// Getters and Setters
		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getType() {
			return type;
		}

		public void setType(String type) {
			this.type = type;
		}

		public String getScheme() {
			return scheme;
		}

		public void setScheme(String scheme) {
			this.scheme = scheme;
		}

		public String getBearerFormat() {
			return bearerFormat;
		}

		public void setBearerFormat(String bearerFormat) {
			this.bearerFormat = bearerFormat;
		}

		public String getDescription() {
			return description;
		}

		public void setDescription(String description) {
			this.description = description;
		}

		public String getIn() {
			return in;
		}

		public void setIn(String in) {
			this.in = in;
		}

		public String getParamName() {
			return paramName;
		}

		public void setParamName(String paramName) {
			this.paramName = paramName;
		}

		public String getFlow() {
			return flow;
		}

		public void setFlow(String flow) {
			this.flow = flow;
		}

		public String getAuthorizationUrl() {
			return authorizationUrl;
		}

		public void setAuthorizationUrl(String authorizationUrl) {
			this.authorizationUrl = authorizationUrl;
		}

		public String getTokenUrl() {
			return tokenUrl;
		}

		public void setTokenUrl(String tokenUrl) {
			this.tokenUrl = tokenUrl;
		}

		public String getOpenIdConnectUrl() {
			return openIdConnectUrl;
		}

		public void setOpenIdConnectUrl(String openIdConnectUrl) {
			this.openIdConnectUrl = openIdConnectUrl;
		}

		public Map<String, String> getScopes() {
			return scopes;
		}

		public void setScopes(Map<String, String> scopes) {
			this.scopes = scopes;
		}

	}

}
