// ********RoostGPT********
/*
Test generated by RoostGPT for test API-test-REST using AI Type Claude AI and AI Model claude-opus-4-5-20251101

Test generated for /auth/register_post for http method type POST in rest-assured framework

RoostTestHash=e65b88515f

[
  {
    "ScenarioID": "1",
    "TestName": "testValidUserRegistrationReturns201",
    "Description": "Test successful user registration with all valid fields",
    "Execution": {
      "Arrange": "Prepare a valid request body with username, email, firstName, and lastName fields",
      "Act": "Send POST request to /auth/register with valid JSON body containing all required user details",
      "Assert": "Check for 201 status, response body contains id, username, email, firstName, lastName, and createdAt fields"
    },
    "Validation": "Ensures API successfully creates a new user with valid input data"
  },
  {
    "ScenarioID": "2",
    "TestName": "testRegistrationWithMinimalRequiredFields",
    "Description": "Test user registration with only mandatory fields",
    "Execution": {
      "Arrange": "Prepare request body with only username and email fields",
      "Act": "Send POST request to /auth/register with minimal required fields",
      "Assert": "Check for 201 status and response contains user data with generated id and createdAt"
    },
    "Validation": "Ensures API accepts registration with minimal required data"
  },
  {
    "ScenarioID": "3",
    "TestName": "testRegistrationWithMissingUsername",
    "Description": "Test registration fails when username is missing",
    "Execution": {
      "Arrange": "Prepare request body without username field, include email and other fields",
      "Act": "Send POST request to /auth/register without username",
      "Assert": "Check for 400 status, response contains error code 400 and message indicating missing username"
    },
    "Validation": "Ensures API validates presence of username field"
  },
  {
    "ScenarioID": "4",
    "TestName": "testRegistrationWithMissingEmail",
    "Description": "Test registration fails when email is missing",
    "Execution": {
      "Arrange": "Prepare request body without email field, include username and other fields",
      "Act": "Send POST request to /auth/register without email",
      "Assert": "Check for 400 status, response contains error code 400 and message indicating missing email"
    },
    "Validation": "Ensures API validates presence of email field"
  },
  {
    "ScenarioID": "5",
    "TestName": "testRegistrationWithInvalidEmailFormat",
    "Description": "Test registration fails with malformed email address",
    "Execution": {
      "Arrange": "Prepare request body with invalid email format like 'invalid-email' or 'user@'",
      "Act": "Send POST request to /auth/register with invalid email format",
      "Assert": "Check for 400 status, response contains error details about invalid email format"
    },
    "Validation": "Ensures API validates email format according to RFC standards"
  },
  {
    "ScenarioID": "6",
    "TestName": "testRegistrationWithEmptyRequestBody",
    "Description": "Test registration fails with empty request body",
    "Execution": {
      "Arrange": "Prepare an empty JSON object as request body",
      "Act": "Send POST request to /auth/register with empty body {}",
      "Assert": "Check for 400 status, response contains error code and message about missing required fields"
    },
    "Validation": "Ensures API rejects empty registration requests"
  },
  {
    "ScenarioID": "7",
    "TestName": "testRegistrationWithNullUsername",
    "Description": "Test registration fails when username is null",
    "Execution": {
      "Arrange": "Prepare request body with username set to null",
      "Act": "Send POST request to /auth/register with username: null",
      "Assert": "Check for 400 status, response indicates invalid username value"
    },
    "Validation": "Ensures API rejects null values for username"
  },
  {
    "ScenarioID": "8",
    "TestName": "testRegistrationWithNullEmail",
    "Description": "Test registration fails when email is null",
    "Execution": {
      "Arrange": "Prepare request body with email set to null",
      "Act": "Send POST request to /auth/register with email: null",
      "Assert": "Check for 400 status, response indicates invalid email value"
    },
    "Validation": "Ensures API rejects null values for email"
  },
  {
    "ScenarioID": "9",
    "TestName": "testRegistrationWithEmptyStringUsername",
    "Description": "Test registration fails when username is empty string",
    "Execution": {
      "Arrange": "Prepare request body with username as empty string",
      "Act": "Send POST request to /auth/register with username: ''",
      "Assert": "Check for 400 status, response contains error about invalid username"
    },
    "Validation": "Ensures API rejects empty string for username"
  },
  {
    "ScenarioID": "10",
    "TestName": "testRegistrationWithEmptyStringEmail",
    "Description": "Test registration fails when email is empty string",
    "Execution": {
      "Arrange": "Prepare request body with email as empty string",
      "Act": "Send POST request to /auth/register with email: ''",
      "Assert": "Check for 400 status, response contains error about invalid email"
    },
    "Validation": "Ensures API rejects empty string for email"
  },
  {
    "ScenarioID": "11",
    "TestName": "testRegistrationWithNumericUsername",
    "Description": "Test registration with numeric value for username instead of string",
    "Execution": {
      "Arrange": "Prepare request body with username as integer 12345",
      "Act": "Send POST request to /auth/register with username: 12345",
      "Assert": "Check for 400 status or type coercion behavior"
    },
    "Validation": "Ensures API validates username type as string"
  },
  {
    "ScenarioID": "12",
    "TestName": "testRegistrationWithArrayUsername",
    "Description": "Test registration fails when username is an array",
    "Execution": {
      "Arrange": "Prepare request body with username as array ['user1', 'user2']",
      "Act": "Send POST request to /auth/register with username as array",
      "Assert": "Check for 400 status, response indicates type mismatch"
    },
    "Validation": "Ensures API rejects wrong data types for username"
  },
  {
    "ScenarioID": "13",
    "TestName": "testRegistrationWithObjectEmail",
    "Description": "Test registration fails when email is an object",
    "Execution": {
      "Arrange": "Prepare request body with email as object {value: 'test@test.com'}",
      "Act": "Send POST request to /auth/register with email as object",
      "Assert": "Check for 400 status, response indicates type mismatch"
    },
    "Validation": "Ensures API rejects wrong data types for email"
  },
  {
    "ScenarioID": "14",
    "TestName": "testRegistrationWithVeryLongUsername",
    "Description": "Test registration with extremely long username string",
    "Execution": {
      "Arrange": "Prepare request body with username containing 10000 characters",
      "Act": "Send POST request to /auth/register with very long username",
      "Assert": "Check for 400 status or appropriate handling of oversized input"
    },
    "Validation": "Ensures API handles boundary conditions for username length"
  },
  {
    "ScenarioID": "15",
    "TestName": "testRegistrationWithSpecialCharactersInUsername",
    "Description": "Test registration with special characters in username",
    "Execution": {
      "Arrange": "Prepare request body with username containing special chars like '@#$%^&*()'",
      "Act": "Send POST request to /auth/register with special character username",
      "Assert": "Check response status and validate if special characters are allowed or rejected"
    },
    "Validation": "Ensures API properly handles special characters in username"
  },
  {
    "ScenarioID": "16",
    "TestName": "testRegistrationWithUnicodeCharacters",
    "Description": "Test registration with unicode characters in name fields",
    "Execution": {
      "Arrange": "Prepare request body with firstName and lastName containing unicode like 'Müller' or '田中'",
      "Act": "Send POST request to /auth/register with unicode characters",
      "Assert": "Check for 201 status and proper handling of unicode in response"
    },
    "Validation": "Ensures API supports international character sets"
  },
  {
    "ScenarioID": "17",
    "TestName": "testRegistrationWithMalformedJSON",
    "Description": "Test registration fails with malformed JSON body",
    "Execution": {
      "Arrange": "Prepare malformed JSON string like '{username: jdoe, email: test@test.com'",
      "Act": "Send POST request to /auth/register with malformed JSON",
      "Assert": "Check for 400 status, response indicates JSON parsing error"
    },
    "Validation": "Ensures API properly handles malformed JSON requests"
  },
  {
    "ScenarioID": "18",
    "TestName": "testRegistrationWithNoContentType",
    "Description": "Test registration without Content-Type header",
    "Execution": {
      "Arrange": "Prepare valid request body but omit Content-Type header",
      "Act": "Send POST request to /auth/register without Content-Type header",
      "Assert": "Check for 400 status or appropriate error response"
    },
    "Validation": "Ensures API requires proper Content-Type header"
  },
  {
    "ScenarioID": "19",
    "TestName": "testRegistrationWithWrongContentType",
    "Description": "Test registration with incorrect Content-Type header",
    "Execution": {
      "Arrange": "Prepare valid JSON body but set Content-Type to text/plain",
      "Act": "Send POST request to /auth/register with Content-Type: text/plain",
      "Assert": "Check for 400 status or unsupported media type error"
    },
    "Validation": "Ensures API validates Content-Type header"
  },
  {
    "ScenarioID": "20",
    "TestName": "testRegistrationWithDuplicateEmail",
    "Description": "Test registration fails when email already exists",
    "Execution": {
      "Arrange": "First register a user with email 'existing@example.com', then prepare another request with same email",
      "Act": "Send POST request to /auth/register with duplicate email",
      "Assert": "Check for 400 status, response indicates email already in use"
    },
    "Validation": "Ensures API prevents duplicate email registrations"
  },
  {
    "ScenarioID": "21",
    "TestName": "testRegistrationWithDuplicateUsername",
    "Description": "Test registration fails when username already exists",
    "Execution": {
      "Arrange": "First register a user with username 'existinguser', then prepare another request with same username",
      "Act": "Send POST request to /auth/register with duplicate username",
      "Assert": "Check for 400 status, response indicates username already taken"
    },
    "Validation": "Ensures API prevents duplicate username registrations"
  },
  {
    "ScenarioID": "22",
    "TestName": "testRegistrationWithWhitespaceOnlyUsername",
    "Description": "Test registration fails when username contains only whitespace",
    "Execution": {
      "Arrange": "Prepare request body with username as '   ' (spaces only)",
      "Act": "Send POST request to /auth/register with whitespace username",
      "Assert": "Check for 400 status, response indicates invalid username"
    },
    "Validation": "Ensures API rejects whitespace-only usernames"
  },
  {
    "ScenarioID": "23",
    "TestName": "testRegistrationWithLeadingTrailingSpacesInEmail",
    "Description": "Test registration handles email with leading/trailing spaces",
    "Execution": {
      "Arrange": "Prepare request body with email as '  test@example.com  '",
      "Act": "Send POST request to /auth/register with padded email",
      "Assert": "Check if API trims spaces and returns 201 or rejects with 400"
    },
    "Validation": "Ensures API properly handles whitespace in email field"
  },
  {
    "ScenarioID": "24",
    "TestName": "testRegistrationWithSQLInjectionInUsername",
    "Description": "Test registration handles SQL injection attempt in username",
    "Execution": {
      "Arrange": "Prepare request body with username as 'admin'; DROP TABLE users;--'",
      "Act": "Send POST request to /auth/register with SQL injection payload",
      "Assert": "Check for 400 status or safe handling without SQL execution"
    },
    "Validation": "Ensures API is protected against SQL injection attacks"
  },
  {
    "ScenarioID": "25",
    "TestName": "testRegistrationWithXSSInFirstName",
    "Description": "Test registration handles XSS attempt in firstName",
    "Execution": {
      "Arrange": "Prepare request body with firstName as '<script>alert(1)</script>'",
      "Act": "Send POST request to /auth/register with XSS payload",
      "Assert": "Check that response properly escapes or sanitizes the input"
    },
    "Validation": "Ensures API is protected against XSS attacks"
  },
  {
    "ScenarioID": "26",
    "TestName": "testRegistrationWithExtraUnknownFields",
    "Description": "Test registration with additional unknown fields in body",
    "Execution": {
      "Arrange": "Prepare request body with valid fields plus extra fields like 'role': 'admin', 'isVerified': true",
      "Act": "Send POST request to /auth/register with extra fields",
      "Assert": "Check for 201 status and verify extra fields are ignored in response"
    },
    "Validation": "Ensures API ignores unknown fields and processes valid ones"
  },
  {
    "ScenarioID": "27",
    "TestName": "testRegistrationWithBooleanFirstName",
    "Description": "Test registration fails when firstName is boolean",
    "Execution": {
      "Arrange": "Prepare request body with firstName as true",
      "Act": "Send POST request to /auth/register with boolean firstName",
      "Assert": "Check for 400 status indicating type mismatch"
    },
    "Validation": "Ensures API validates firstName type as string"
  },
  {
    "ScenarioID": "28",
    "TestName": "testRegistrationResponseContainsCreatedAt",
    "Description": "Test that successful registration returns valid createdAt timestamp",
    "Execution": {
      "Arrange": "Prepare valid registration request body",
      "Act": "Send POST request to /auth/register with valid data",
      "Assert": "Check for 201 status and createdAt field is valid ISO 8601 date-time format"
    },
    "Validation": "Ensures API returns properly formatted createdAt timestamp"
  },
  {
    "ScenarioID": "29",
    "TestName": "testRegistrationResponseContainsGeneratedId",
    "Description": "Test that successful registration returns generated user id",
    "Execution": {
      "Arrange": "Prepare valid registration request body",
      "Act": "Send POST request to /auth/register with valid data",
      "Assert": "Check for 201 status and id field is present and non-empty string"
    },
    "Validation": "Ensures API generates and returns unique user id"
  },
  {
    "ScenarioID": "30",
    "TestName": "testRegistrationWithCaseInsensitiveEmail",
    "Description": "Test registration handles email case sensitivity",
    "Execution": {
      "Arrange": "Register user with 'Test@Example.com', then try registering with 'test@example.com'",
      "Act": "Send POST request to /auth/register with different case email",
      "Assert": "Check if API treats emails as case-insensitive and returns 400 for duplicate"
    },
    "Validation": "Ensures API handles email case sensitivity correctly"
  }
]

*/

// ********RoostGPT********
package RestAssured.RoostTest.openapi_configuration;

import RestAssured.RoostTest.openapi_configuration.auth.UnifiedAuthHandler;
import RestAssured.RoostTest.openapi_configuration.utils.ResponseValidator;
import RestAssured.RoostTest.openapi_configuration.utils.SchemaModels.ResponseSchema;
import RestAssured.RoostTest.openapi_configuration.utils.SchemaModels.FieldConstraint;
import RestAssured.RoostTest.openapi_configuration.utils.SchemaModels.NumericConstraint;
import RestAssured.RoostTest.openapi_configuration.utils.SchemaModels.StringConstraint;
import RestAssured.RoostTest.openapi_configuration.utils.SchemaModels.ArrayConstraint;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import io.restassured.http.ContentType;
import static io.restassured.RestAssured.given;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterAll;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.File;
import java.io.IOException;
import java.util.*;

public class AuthRegisterPostTest {

	private static final Logger logger = LoggerFactory.getLogger(AuthRegisterPostTest.class);

	private static UnifiedAuthHandler authHandler;

	private static ResponseValidator responseValidator;

	private static ObjectMapper objectMapper;

	private static final String BASE_URI = "http://localhost:8080/OpenAPIExample/";

	private static final String ENDPOINT = "/auth/register";

	private static final String HTTP_METHOD = "post";

	private static final String TEST_DATA_FILE = "src/test/java/RestAssured/RoostTest/openapi_configuration/datasets/auth_registerPostTest.json";

	private static List<String> failedTests = new ArrayList<>();

	private static int totalTests = 0;

	private static int passedTests = 0;

	private static int failedTestsCount = 0;

	@BeforeAll
	public static void setup() {
		authHandler = new UnifiedAuthHandler();
		responseValidator = new ResponseValidator();
		objectMapper = new ObjectMapper();

		String baseUrl = authHandler.getBaseUrl();
		if (baseUrl == null || baseUrl.isEmpty()) {
			RestAssured.baseURI = BASE_URI;
		}
		else {
			RestAssured.baseURI = baseUrl;
		}

		logger.info("Test setup completed. Base URI: {}", RestAssured.baseURI);
	}

	@Test
	public void testEndpoint() {
		List<Map<String, Object>> testCases = loadTestData();
		Map<String, ParameterInfo> parameters = getParameters();
		SecurityInfo security = getSecurityInfo();
		Map<Integer, ResponseSchema> schemas = getResponseSchemas();

		for (Map<String, Object> testCase : testCases) {
			totalTests++;
			String scenario = testCase.containsKey("scenario") ? testCase.get("scenario").toString()
					: "Test case " + totalTests;

			try {
				logger.info("Executing test {}/{}: {}", totalTests, testCases.size(), scenario);

				Object statusCodeObj = testCase.get("expected_statusCode");
				if (statusCodeObj == null) {
					logger.error("Test case missing 'expected_statusCode' field: {}", scenario);
					failedTests.add(scenario + " - Missing expected_statusCode");
					failedTestsCount++;
					continue;
				}
				int expectedStatusCode = ((Number) statusCodeObj).intValue();

				String authValidityType = (expectedStatusCode == 401) ? "invalid" : "valid";

				Response response = executeTest(testCase, parameters, security, authValidityType);

				ResponseSchema schema = schemas.get(expectedStatusCode);
				if (schema == null) {
					schema = schemas.get(0);
				}

				String contentType = response.getHeader("Content-Type");
				if (contentType != null && contentType.toLowerCase().contains("application/json")) {
					responseValidator.validateResponse(response, expectedStatusCode, schema);
					logger.info("Response validation completed for JSON content type");
				}
				else {
					if (response.getStatusCode() == expectedStatusCode) {
						logger.info(
								"Status code validation passed: expected {}, actual {}. Response body validation skipped for content-type: {}",
								expectedStatusCode, response.getStatusCode(),
								contentType != null ? contentType : "not specified");
					}
					else {
						throw new AssertionError(String.format(
								"Status code mismatch: expected %d, but got %d. Response body validation skipped for content-type: %s",
								expectedStatusCode, response.getStatusCode(),
								contentType != null ? contentType : "not specified"));
					}
				}

				passedTests++;
				logger.info("✓ Test passed: {}", scenario);

			}
			catch (Throwable e) {
				failedTestsCount++;
				failedTests.add(scenario + " - " + e.getMessage());
				logger.error("✗ Test failed: {} - Error: {}", scenario, e.getMessage());
			}
		}
	}

	@AfterAll
	public static void tearDown() {
		logger.info("\n=== Test Execution Summary ===");
		logger.info("Total tests: {}", totalTests);
		logger.info("Passed: {}", passedTests);
		logger.info("Failed: {}", failedTestsCount);

		if (failedTestsCount > 0) {
			logger.info("\nFailed test scenarios:");
			for (String failedTest : failedTests) {
				logger.info("  - {}", failedTest);
			}
		}
	}

	private Response executeTest(Map<String, Object> testCase, Map<String, ParameterInfo> parameters,
			SecurityInfo security, String authValidityType) {
		Map<String, Object> queryParams = new HashMap<>();
		Map<String, Object> pathParams = new HashMap<>();
		Map<String, Object> headerParams = new HashMap<>();
		Map<String, Object> bodyParams = new HashMap<>();

		for (Map.Entry<String, Object> entry : testCase.entrySet()) {
			String key = entry.getKey();
			Object value = entry.getValue();

			if (key.equals("scenario") || key.equals("expected_statusCode")) {
				continue;
			}

			ParameterInfo paramInfo = parameters.get(key);
			if (paramInfo != null) {
				String location = paramInfo.getLocation();
				switch (location) {
					case "query":
						queryParams.put(key, value);
						break;
					case "path":
						pathParams.put(key, value);
						break;
					case "header":
						headerParams.put(key, value);
						break;
					case "body":
						bodyParams.put(key, value);
						break;
					default:
						bodyParams.put(key, value);
						break;
				}
			}
			else {
				bodyParams.put(key, value);
			}
		}

		RequestSpecification request = given().contentType(ContentType.JSON).accept(ContentType.JSON);

		if (security != null && security.getSchemeName() != null && authHandler.hasScheme(security.getSchemeName())) {
			request = authHandler.applyAuth(request, security.getSchemeName(), authValidityType);
		}

		if (!queryParams.isEmpty()) {
			request = request.queryParams(queryParams);
		}

		if (!pathParams.isEmpty()) {
			request = request.pathParams(pathParams);
		}

		if (!headerParams.isEmpty()) {
			for (Map.Entry<String, Object> header : headerParams.entrySet()) {
				request = request.header(header.getKey(), header.getValue());
			}
		}

		if (!bodyParams.isEmpty()) {
			request = request.body(bodyParams);
		}

		return request.when().post(ENDPOINT);
	}

	private Map<String, ParameterInfo> getParameters() {
		Map<String, ParameterInfo> parameters = new HashMap<>();

		parameters.put("username", new ParameterInfo("username", "body", "string", true));
		parameters.put("email", new ParameterInfo("email", "body", "string", true));
		parameters.put("password", new ParameterInfo("password", "body", "string", true));

		return parameters;
	}

	private SecurityInfo getSecurityInfo() {
		return new SecurityInfo("bearerAuth", "http", "Authorization", "header");
	}

	private Map<Integer, ResponseSchema> getResponseSchemas() {
		Map<Integer, ResponseSchema> schemas = new HashMap<>();

		// Schema for 201 response
		ResponseSchema schema201 = new ResponseSchema();
		Map<String, FieldConstraint> fields201 = new HashMap<>();

		FieldConstraint idField = new FieldConstraint("string");
		fields201.put("id", idField);

		FieldConstraint usernameField = new FieldConstraint("string");
		fields201.put("username", usernameField);

		FieldConstraint emailField = new FieldConstraint("string").setFormat("email");
		fields201.put("email", emailField);

		FieldConstraint firstNameField = new FieldConstraint("string");
		fields201.put("firstName", firstNameField);

		FieldConstraint lastNameField = new FieldConstraint("string");
		fields201.put("lastName", lastNameField);

		FieldConstraint createdAtField = new FieldConstraint("string").setFormat("date-time");
		fields201.put("createdAt", createdAtField);

		schema201.setFields(fields201);
		schemas.put(201, schema201);

		// Schema for 400 response
		ResponseSchema schema400 = new ResponseSchema();
		Map<String, FieldConstraint> fields400 = new HashMap<>();

		FieldConstraint codeField = new FieldConstraint("integer");
		fields400.put("code", codeField);

		FieldConstraint messageField = new FieldConstraint("string");
		fields400.put("message", messageField);

		FieldConstraint detailsField = new FieldConstraint("array").setItemsConstraint(new FieldConstraint("string"));
		fields400.put("details", detailsField);

		schema400.setFields(fields400);
		schemas.put(400, schema400);

		return schemas;
	}

	private List<Map<String, Object>> loadTestData() {
		try {
			File file = new File(TEST_DATA_FILE);
			return objectMapper.readValue(file, new TypeReference<List<Map<String, Object>>>() {
			});
		}
		catch (IOException e) {
			logger.error("Failed to load test data from {}: {}", TEST_DATA_FILE, e.getMessage());
			return new ArrayList<>();
		}
	}

	private static class ParameterInfo {

		private final String name;

		private final String location;

		private final String type;

		private final boolean required;

		public ParameterInfo(String name, String location, String type, boolean required) {
			this.name = name;
			this.location = location;
			this.type = type;
			this.required = required;
		}

		public String getName() {
			return name;
		}

		public String getLocation() {
			return location;
		}

		public String getType() {
			return type;
		}

		public boolean isRequired() {
			return required;
		}

	}

	private static class SecurityInfo {

		private final String schemeName;

		private final String type;

		private final String credentialName;

		private final String location;

		public SecurityInfo(String schemeName, String type, String credentialName, String location) {
			this.schemeName = schemeName;
			this.type = type;
			this.credentialName = credentialName;
			this.location = location;
		}

		public String getSchemeName() {
			return schemeName;
		}

		public String getType() {
			return type;
		}

		public String getCredentialName() {
			return credentialName;
		}

		public String getLocation() {
			return location;
		}

	}

}
