# ********RoostGPT********

# Test generated by RoostGPT for test API-Test-with-Karate using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /items/{item_id}/{name}_get for http method type GET 
# RoostTestHash=0c3f2f6e78
# 
# 

# ********RoostGPT********
Feature: Test API Endpoint /items/{item_id}/{name}

  Background:
    * def baseURL = karate.properties['FASTAPI_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Test GET /items/{item_id}/{name} with valid parameters
    Given path 'items', <item_id>, <name>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.item_id == '#string'
    And match response.value == '#string'
    And match response.name == '#string'

    Examples:
      | item_id | name    |
      | 1       | 'name1' |
      | 2       | 'name2' |
      | 3       | 'name3' |

  Scenario Outline: Test GET /items/{item_id}/{name} with invalid item_id
    Given path 'items', <item_id>, <name>
    When method GET
    Then assert responseStatus != 200
    And match response.error == '#object'
    And match response.error.code == '#string'
    And match response.error.message == '#string'

    Examples:
      | item_id | name    |
      | 'abc'   | 'name1' |
      | -1      | 'name2' |
      | 0       | 'name3' |

  Scenario Outline: Test GET /items/{item_id}/{name} with invalid name
    Given path 'items', <item_id>, <name>
    When method GET
    Then assert responseStatus != 200
    And match response.error == '#object'
    And match response.error.code == '#string'
    And match response.error.message == '#string'

    Examples:
      | item_id | name      |
      | 1       | ''        |
      | 2       | ' '       |
      | 3       | 'invalid' |
